Feat: ProxyOracle, refactoring
dmitryn2018/protocol-v2 pull request #2
Opened 2022-10-11 12:44 UTC by Oladiy

2022-10-11 15:07 UTC, DZahar0v requested changes

2022-10-11 15:07 UTC, DZahar0v commented on contracts/interfaces/IChainlinkAggregator.sol
> +  function latestRoundData()
You should add another interface that will contain latestRoundData()

2022-10-11 15:07 UTC, DZahar0v commented on contracts/misc/ProxyOracle.sol
> +  function latestRoundData()
Do we need this function here?

2022-10-11 15:07 UTC, DZahar0v commented on tasks/dev/4_oracles.ts
> +    await waitForTx(await addressesProvider.setPriceOracle(fallbackOracle.address));
It should be aaveOracle

2022-10-11 15:07 UTC, DZahar0v commented on tasks/migrations/aave.dev.ts
>      // NOTE: checking chainlink oracle
Do not remove price checking

2022-10-11 15:07 UTC, DZahar0v commented on tasks/migrations/aave.neon.ts
> +    console.log(DAI.address);
Remove this log

2022-10-11 15:07 UTC, DZahar0v commented on tasks/migrations/aave.neon.ts
>        'User 1 USDC: ',
Update log text

2022-10-11 15:33 UTC, Oladiy commented on tasks/migrations/aave.neon.ts
> +    console.log(DAI.address);
> Remove this log

Done

2022-10-11 15:33 UTC, Oladiy commented on contracts/interfaces/IChainlinkAggregator.sol
> +  function latestRoundData()
> You should add another interface that will contain latestRoundData()

Done

2022-10-11 15:33 UTC, Oladiy commented on contracts/misc/ProxyOracle.sol
> +  function latestRoundData()
> Do we need this function here?

Done. Removed redundant function

2022-10-11 15:33 UTC, Oladiy commented on tasks/dev/4_oracles.ts
> +    await waitForTx(await addressesProvider.setPriceOracle(fallbackOracle.address));
> It should be aaveOracle

Done

2022-10-11 15:35 UTC, Oladiy commented on tasks/migrations/aave.dev.ts
>      // NOTE: checking chainlink oracle
> Do not remove price checking

Done

2022-10-12 07:03 UTC, Oladiy commented on tasks/migrations/aave.neon.ts
>        'User 1 USDC: ',
> Update log text

Done

2022-10-12 08:49 UTC, Oladiy commented on tasks/migrations/aave.dev.ts
>      // NOTE: checking chainlink oracle
> Do not remove price checking

Done

2022-10-12 10:02 UTC, merged